name: monochrome
description: monochrome
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  signature:
  flutter_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Titillium
      fonts:
        - asset: fonts/TitilliumWeb-Black.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
        - asset: fonts/TitilliumWeb-SemiBold.ttf
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-ExtraLight.ttf
        - asset: fonts/TitilliumWeb-light.ttf